spring:
  rabbitmq:
    addresses: ${RABBIT_ADDRESSES:localhost:5671}
    username: ${RABBIT_USERNAME:guest}
    password: ${RABBIT_PASSWORD:guest}

app:
  scheduler:
    cron:
      fetch-rates-period: "0 0/2 * * * ?"
  client:
    base-url: "https://api.nbp.pl/api/exchangerates"
  queue-name: rates_queue
server:
  port: ${APP_PORT:8085}