spring:
  rabbitmq:
    queue-name: rates_queue
    host: localhost
    username: guest
    password: guest
    port: 5672

app:
  scheduler:
    cron:
      fetch-rates-period: "* * * * * ?"
  client:
    base-url: "https://api.nbp.pl/api/exchangerates"

server:
  port: 8081